services:
  migrator:
    image: ghcr.io/nirajshaha/cobol-migration-automation:${IMAGE_TAG:-latest}
    pull_policy: always
    env_file:
      - .env
    volumes:
      - ./input:/app/input
      - ./output:/app/output
    command: ["--help"]
    restart: "no"
